# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./docker/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8181:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
    mysql:
        image: "mysql:5.7"
        user: "mysql"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=foo_commerce
        ports:
          - "33067:3306"
        networks:
            - sail
    mysql-test:
        image: "mysql:5.7"
        user: "mysql"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=foo_commerce
        ports:
          - "33068:3306"
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
